export const SET_HOW_MANY_ANSWERS = 'SET_HOW_MANY_ANSWERS'

export const SET_QUESTION = 'SET_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS'

export const SET_QUIZ_TITLE = 'SET_QUIZ_TITLE'
export const SET_NUMBER_OF_ANSWERS = 'SET_NUMBER_OF_ANSWERS'
export const SET_QUIZ_ID = 'SET_QUIZ_ID'
export const SET_RESULTS = 'SET_RESULTS'
export const SET_RESULTS_OF_QUIZ_TAKEN = 'SET_RESULTS'